# Generated by Django 5.2.12 on 2026-03-15 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panels', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='panel_face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='panels.panelface'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['agency', 'status'], name='reservation_agency__e62986_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['panel_face', 'status'], name='reservation_panel_f_09ec02_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['start_date', 'end_date'], name='reservation_start_d_30a023_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['source'], name='reservation_source_304545_idx'),
        ),
    ]
