# Generated by Django 5.2.12 on 2026-04-26 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('reservations', '0003_reservationstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='agencies.agency'),
        ),
    ]
