# Generated by Django 5.2.12 on 2026-07-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_client_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='interrupted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='interrupted_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='interrupted_reason',
            field=models.CharField(blank=True, choices=[('unpaid', 'Non-paiement / impayé client'), ('client_request', 'Demande du client'), ('technical_issue', 'Dégradation ou problème technique du support'), ('force_majeure', 'Force majeure'), ('regulatory_order', "Injonction d'une autorité de régulation"), ('commercial_dispute', 'Litige commercial'), ('agency_decision', 'Décision de la régie'), ('other', 'Autre')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('interrupted', 'Interrupted')], default='pending', max_length=20),
        ),
    ]
