# Generated by Django 5.2.12 on 2026-07-21 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_interrupted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationTaxLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('line_type', models.CharField(choices=[('addition', 'Ajout (taxe facturée en plus au client)'), ('deduction', 'Retenue (déduite du montant net à percevoir)')], max_length=20)),
                ('computation_mode', models.CharField(choices=[('percentage', 'Pourcentage du montant'), ('fixed', 'Montant fixe')], max_length=20)),
                ('rate_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_lines', to='reservations.reservation')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
