# Generated by Django 5.2.12 on 2026-03-14 14:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('format', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='agencies.agency')),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='PanelFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'Face A'), ('B', 'Face B')], max_length=1)),
                ('orientation', models.CharField(blank=True, max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('operational_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='panels.panel')),
            ],
            options={
                'ordering': ['panel', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='panel',
            index=models.Index(fields=['agency', 'status'], name='panels_pane_agency__53dc08_idx'),
        ),
        migrations.AddIndex(
            model_name='panel',
            index=models.Index(fields=['city'], name='panels_pane_city_508dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='panel',
            index=models.Index(fields=['district'], name='panels_pane_distric_6111b3_idx'),
        ),
        migrations.AddIndex(
            model_name='panel',
            index=models.Index(fields=['is_published'], name='panels_pane_is_publ_f1ef2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='panel',
            constraint=models.UniqueConstraint(fields=('agency', 'reference'), name='unique_panel_reference_per_agency'),
        ),
        migrations.AddIndex(
            model_name='panelface',
            index=models.Index(fields=['panel', 'code'], name='panels_pane_panel_i_1b5724_idx'),
        ),
        migrations.AddIndex(
            model_name='panelface',
            index=models.Index(fields=['operational_status'], name='panels_pane_operati_f1e14f_idx'),
        ),
        migrations.AddConstraint(
            model_name='panelface',
            constraint=models.UniqueConstraint(fields=('panel', 'code'), name='unique_face_code_per_panel'),
        ),
    ]
