# Generated by Django 5.2.12 on 2026-03-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panelface',
            options={'ordering': ['panel__reference', 'code']},
        ),
    ]
