# Generated by Django 5.2.12 on 2026-03-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('locations', '0001_initial'),
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='format',
        ),
        migrations.AddField(
            model_name='panel',
            name='format_category',
            field=models.CharField(choices=[('small', 'Inférieur à 12 m²'), ('standard', 'De 12 à moins de 24 m²'), ('large', '24 m²'), ('xl', 'Supérieur à 24 m²')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='panel',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='width_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddIndex(
            model_name='panel',
            index=models.Index(fields=['format_category'], name='panels_pane_format__460878_idx'),
        ),
    ]
