# Generated by Django 5.2.12 on 2026-03-29 12:44

import apps.panels.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0002_remove_panel_format_panel_format_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.panels.models.panel_image_upload_to)),
                ('image_type', models.CharField(choices=[('face', 'Face du panneau'), ('environment', 'Environnement'), ('other', 'Autre')], default='other', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='panels.panel')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['panel', 'image_type'], name='panels_pane_panel_i_dc3f3b_idx'), models.Index(fields=['panel', 'is_primary'], name='panels_pane_panel_i_8fd4cb_idx')],
            },
        ),
    ]
