# Generated by Django 5.2.12 on 2026-03-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0002_alter_panelface_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panelface',
            options={'ordering': ['panel', 'code']},
        ),
        migrations.AlterField(
            model_name='panelface',
            name='code',
            field=models.CharField(choices=[('A', 'Face A'), ('B', 'Face B'), ('C', 'Face C'), ('D', 'Face D')], max_length=1),
        ),
    ]
