# Generated by Django 5.2.12 on 2026-04-04 11:43

import apps.panels.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0003_panelimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelFaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.panels.models.panel_face_image_upload_to)),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_cover_for_panel', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='panels.panelface')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['face', 'is_primary'], name='panels_pane_face_id_3a0687_idx'), models.Index(fields=['face', 'is_cover_for_panel'], name='panels_pane_face_id_fa1b4b_idx')],
            },
        ),
    ]
