# Generated by Django 5.2.12 on 2026-07-08 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('geography', '0001_initial'),
        ('locations', '0001_initial'),
        ('panels', '0004_panelfaceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='geographic_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='panels', to='geography.geographicunit'),
        ),
        migrations.AddIndex(
            model_name='panel',
            index=models.Index(fields=['geographic_unit'], name='panels_pane_geograp_0d6029_idx'),
        ),
    ]
