# Generated by Django 5.2.12 on 2026-07-09 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('panels', '0005_panel_geographic_unit_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='panel',
            name='panels_pane_distric_6111b3_idx',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='city_ref',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='district',
        ),
        migrations.AlterField(
            model_name='panel',
            name='geographic_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='panels', to='geography.geographicunit'),
            preserve_default=False,
        ),
    ]
