# Generated by Django 5.2.12 on 2026-07-23 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_agency_footer_image_agency_header_image'),
        ('geography', '0001_initial'),
        ('panels', '0006_remove_panel_panels_pane_distric_6111b3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé')], default='in_progress', max_length=20)),
                ('reference_prefix', models.CharField(blank=True, max_length=20)),
                ('next_reference_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='agencies.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('last_geographic_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.geographicunit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PanelImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField()),
                ('headers', models.JSONField(blank=True, default=list)),
                ('values', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('created', 'Créée'), ('skipped', 'Ignorée')], default='pending', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='panels.panelimportbatch')),
                ('created_panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panels.panel')),
            ],
            options={
                'ordering': ['row_index'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_index'), name='unique_row_index_per_batch')],
            },
        ),
    ]
