# Generated by Django 5.2.12 on 2026-07-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0007_panelimportbatch_panelimportrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelimportbatch',
            name='raw_grid',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelimportbatch',
            name='status',
            field=models.CharField(choices=[('configuring', 'Configuration'), ('in_progress', 'En cours'), ('completed', 'Terminé')], default='configuring', max_length=20),
        ),
    ]
