# Generated by Django 5.2.12 on 2026-08-02 12:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0008_panelimportbatch_raw_grid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
