# Generated by Django 5.2.12 on 2026-03-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(choices=[('BF', 'Burkina Faso'), ('CI', 'Côte d’Ivoire'), ('ML', 'Mali'), ('NE', 'Niger'), ('GH', 'Ghana'), ('TG', 'Togo'), ('BJ', 'Bénin'), ('SN', 'Sénégal')], max_length=2)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country_code', 'name'],
                'indexes': [models.Index(fields=['country_code', 'name'], name='locations_c_country_feaaf9_idx'), models.Index(fields=['country_code', 'is_active'], name='locations_c_country_07cf66_idx')],
                'constraints': [models.UniqueConstraint(fields=('country_code', 'name'), name='unique_city_name_per_country'), models.UniqueConstraint(fields=('country_code', 'slug'), name='unique_city_slug_per_country')],
            },
        ),
    ]
