# Generated by Django 5.2.12 on 2026-03-15 23:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(choices=[('BF', 'Burkina Faso'), ('CI', 'Côte d’Ivoire'), ('ML', 'Mali'), ('NE', 'Niger'), ('GH', 'Ghana'), ('TG', 'Togo'), ('BJ', 'Bénin'), ('SN', 'Sénégal')], default='BF', max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Commission rate in percent for platform-acquired new clients.', max_digits=5)),
                ('alert_days_before_expiry', models.PositiveIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='locations.city')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
