# Generated by Django 5.2.12 on 2026-07-09 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='geographic_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='geography.geographicunit'),
        ),
    ]
