# Generated by Django 5.2.12 on 2026-07-09 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_geographic_unit'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='city',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='city_ref',
        ),
        migrations.AlterField(
            model_name='agency',
            name='geographic_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='geography.geographicunit'),
            preserve_default=False,
        ),
    ]
