# Generated by Django 5.2.12 on 2026-07-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_remove_agency_city_remove_agency_city_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='footer_image',
            field=models.ImageField(blank=True, help_text='Bandeau de pied de page pour les documents PDF (PNG/JPG, format large recommandé).', null=True, upload_to='agencies/footers/'),
        ),
        migrations.AddField(
            model_name='agency',
            name='header_image',
            field=models.ImageField(blank=True, help_text="Bandeau d'en-tête pour les documents PDF (PNG/JPG, format large recommandé).", null=True, upload_to='agencies/headers/'),
        ),
    ]
