# Generated by Django 5.2.12 on 2026-07-04 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Code ISO 3166-1 alpha-2, ex: BF, CI, CM', max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeographicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Libellé local du niveau, ex: Ville, District, Commune, Quartier', max_length=50)),
                ('order', models.PositiveSmallIntegerField(help_text='1 = niveau le plus large (juste sous le pays), valeur croissante = niveau le plus fin')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='geography.country')),
            ],
            options={
                'verbose_name': 'Niveau géographique',
                'verbose_name_plural': 'Niveaux géographiques',
                'ordering': ['country', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GeographicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='geography.country')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='geography.geographiclevel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='geography.geographicunit')),
            ],
            options={
                'verbose_name': 'Unité géographique',
                'verbose_name_plural': 'Unités géographiques',
                'ordering': ['country', 'level__order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='geographiclevel',
            constraint=models.UniqueConstraint(fields=('country', 'order'), name='unique_order_per_country'),
        ),
        migrations.AddConstraint(
            model_name='geographiclevel',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='unique_name_per_country'),
        ),
        migrations.AddIndex(
            model_name='geographicunit',
            index=models.Index(fields=['country', 'level'], name='geography_g_country_c3b30c_idx'),
        ),
        migrations.AddConstraint(
            model_name='geographicunit',
            constraint=models.UniqueConstraint(fields=('level', 'parent', 'name'), name='unique_unit_per_parent'),
        ),
    ]
